# permissions for end users to edit grafanaorganizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafanaorganization-editor-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - grafanaorganizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly..org
  resources:
  - grafanaorganizations/status
  verbs:
  - get
